name: MineShell
version: '1.0-SNAPSHOT'
main: dev.briiqn.mineShell.MineShell
api-version: '1.21'
commands:
  shellauth:
    description: Authentication command for MineShell
    usage: /shellauth <subcommand>